quarkus.rest.path=/api
quarkus.http.auth.proactive=false
quarkus.datasource.db-kind=h2
quarkus.hibernate-orm.schema-management.strategy=drop-and-create
mp.jwt.verify.issuer=conduit
smallrye.jwt.new-token.issuer=conduit
smallrye.jwt.new-token.lifespan=86400
%dev.quarkus.datasource.jdbc.url=jdbc:h2:mem:conduit
%test.quarkus.datasource.jdbc.url=jdbc:h2:mem:test
